name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push clean backend to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://AhmadDurrani:$HF_TOKEN@huggingface.co/spaces/AhmadYarAI/MZ-Essence space

          rm -rf space/*
          rm -rf space/.gitignore

          rsync -av \
            --exclude 'venv/' \
            --exclude '.env' \
            --exclude '__pycache__/' \
            --exclude '*.pyc' \
            backend/ space/

          cd space
          git add .
          git commit -m "Deploy clean backend" || echo "No changes to commit"
          git push